### ISSUE TITLE
não atualização da pasta `data` após o `update`

### ISSUE THREAD

**Issue by hslinhares** [splor-mg/armazem-siafi-totais-dados#21]
@fjuniorr  após o último update a pasta `data` não alterou, dando erro no `make check` no repositório `armazem-siafi-dados`. Houve alteração no arquivo em `data-raw`.

**Comment by fjuniorr** [comment]
A atualização não aconteceu porque no Makefile, mesmo depois de https://github.com/splor-mg/armazem-siafi-totais-dados/commit/f7ddf4126bf96a4c82b40b4c801adbaa10baf001, ainda estavamos usando o executavel `python`. Isso gerou o erro `make: python: No such file or directory` no log do Github actions mas estranhamente não paralizou a execução.

A solução finalizada em 945f145deed5f51c91fa2e2c4ef86fc1acc5c30f foi configurar um alias no Dockerfile com `RUN echo 'alias python=python3' >> /etc/bash.bashrc`.

De acordo com o chatGPT o `bashrc`:

**Comment by hslinhares** [comment]
resolução em
https://github.com/splor-mg/armazem-siafi-dados/commit/fbdaaf7ad77ddada9714ee89720b48dae75f0cfd
